<?php

namespace Proxy\__CG__\Entidades\ServiceMe;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TblMejoramientoPriMejoras extends \Entidades\ServiceMe\TblMejoramientoPriMejoras implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'id', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'fecha', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'herramienta', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'arbol', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'titulo', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'descripcion', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'usuario', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'producto', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'estado', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'objetivos'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'id', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'fecha', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'herramienta', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'arbol', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'titulo', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'descripcion', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'usuario', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'producto', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'estado', '' . "\0" . 'Entidades\\ServiceMe\\TblMejoramientoPriMejoras' . "\0" . 'objetivos'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TblMejoramientoPriMejoras $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getObjetivos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjetivos', []);

        return parent::getObjetivos();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setHerramienta($herramienta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHerramienta', [$herramienta]);

        return parent::setHerramienta($herramienta);
    }

    /**
     * {@inheritDoc}
     */
    public function getHerramienta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHerramienta', []);

        return parent::getHerramienta();
    }

    /**
     * {@inheritDoc}
     */
    public function setArbol($arbol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArbol', [$arbol]);

        return parent::setArbol($arbol);
    }

    /**
     * {@inheritDoc}
     */
    public function getArbol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArbol', []);

        return parent::getArbol();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\Entidades\ServiceMe\TblUsuarios $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setProducto(\Entidades\ServiceMe\TblGeneralServicios $producto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProducto', [$producto]);

        return parent::setProducto($producto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducto', []);

        return parent::getProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(\Entidades\ServiceMe\TblGeneralEstados $estado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

}
