<?php

namespace Proxy\__CG__\Entidades\ServiceMe;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TblUsuarios extends \Entidades\ServiceMe\TblUsuarios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'id', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'usuario', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'password', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'nombreInicial', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'nombreFinal', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'apellidoInicial', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'apellidoFinal', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'documento', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'fechaNacimiento', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'fechaExpedicion', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'fijo', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'movil', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'eps', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'arp', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'rr', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'genero', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'correo', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'empresa', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'permiso', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'cargo', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'estado'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'id', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'usuario', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'password', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'nombreInicial', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'nombreFinal', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'apellidoInicial', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'apellidoFinal', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'documento', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'fechaNacimiento', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'fechaExpedicion', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'fijo', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'movil', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'eps', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'arp', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'rr', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'genero', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'correo', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'empresa', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'permiso', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'cargo', '' . "\0" . 'Entidades\\ServiceMe\\TblUsuarios' . "\0" . 'estado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TblUsuarios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreInicial($nombreInicial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreInicial', [$nombreInicial]);

        return parent::setNombreInicial($nombreInicial);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreInicial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreInicial', []);

        return parent::getNombreInicial();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreFinal($nombreFinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreFinal', [$nombreFinal]);

        return parent::setNombreFinal($nombreFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreFinal', []);

        return parent::getNombreFinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidoInicial($apellidoInicial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidoInicial', [$apellidoInicial]);

        return parent::setApellidoInicial($apellidoInicial);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidoInicial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidoInicial', []);

        return parent::getApellidoInicial();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidoFinal($apellidoFinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidoFinal', [$apellidoFinal]);

        return parent::setApellidoFinal($apellidoFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidoFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidoFinal', []);

        return parent::getApellidoFinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumento($documento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumento', [$documento]);

        return parent::setDocumento($documento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumento', []);

        return parent::getDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNacimiento($fechaNacimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNacimiento', [$fechaNacimiento]);

        return parent::setFechaNacimiento($fechaNacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNacimiento', []);

        return parent::getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaExpedicion($fechaExpedicion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaExpedicion', [$fechaExpedicion]);

        return parent::setFechaExpedicion($fechaExpedicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaExpedicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaExpedicion', []);

        return parent::getFechaExpedicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFijo($fijo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFijo', [$fijo]);

        return parent::setFijo($fijo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFijo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFijo', []);

        return parent::getFijo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMovil($movil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMovil', [$movil]);

        return parent::setMovil($movil);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovil', []);

        return parent::getMovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setEps($eps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEps', [$eps]);

        return parent::setEps($eps);
    }

    /**
     * {@inheritDoc}
     */
    public function getEps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEps', []);

        return parent::getEps();
    }

    /**
     * {@inheritDoc}
     */
    public function setArp($arp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArp', [$arp]);

        return parent::setArp($arp);
    }

    /**
     * {@inheritDoc}
     */
    public function getArp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArp', []);

        return parent::getArp();
    }

    /**
     * {@inheritDoc}
     */
    public function setRr($rr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRr', [$rr]);

        return parent::setRr($rr);
    }

    /**
     * {@inheritDoc}
     */
    public function getRr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRr', []);

        return parent::getRr();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenero($genero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenero', [$genero]);

        return parent::setGenero($genero);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenero', []);

        return parent::getGenero();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo($correo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', [$correo]);

        return parent::setCorreo($correo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', []);

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa(\Entidades\ServiceMe\TblGeneralEmpresas $empresa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', [$empresa]);

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', []);

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermiso(\Entidades\ServiceMe\TblPermisos $permiso = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermiso', [$permiso]);

        return parent::setPermiso($permiso);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermiso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermiso', []);

        return parent::getPermiso();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargo(\Entidades\ServiceMe\TblGeneralCargo $cargo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargo', [$cargo]);

        return parent::setCargo($cargo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargo', []);

        return parent::getCargo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(\Entidades\ServiceMe\TblGeneralEstados $estado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

}
